version: '3.8'

services:
  userdb:
    image: mongo:8.0
    container_name: userdb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  userapp:
    build: .
    container_name: userapp
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_URI: mongodb://root:rootpassword@userdb:27017/mydatabase?authSource=admin
    depends_on:
      - userdb

volumes:
  mongo-data:

